### ISSUE TITLE
tz.list @mention not working

### ISSUE THREAD

**Issue by EmilyLove26** [NoiTheCat/WorldTime#1]
![image](https://user-images.githubusercontent.com/7028351/74360410-08b78e80-4d93-11ea-851e-fcea2eac9a48.png)

As you see in the picture above, when I try to use tz.list by mention, it fails to find the user. Using the ID or unmentioned name works though. Can we make it so mentions also work?

Feel free to reach out to me on discord, if you need any clarification:
![image](https://user-images.githubusercontent.com/7028351/74360784-add26700-4d93-11ea-812a-cf2bdc039d17.png)

**Comment by NoiTheCat** [comment]
Hello, I'm really sorry for the astonishingly late reply. I do believe one of the fixes made between then and now has fixed the issue, and I specifically tested this scenario when working on the most recent rewrite. Thank you for bringing this to my attention!
