### ISSUE TITLE
Not reading CST

### ISSUE THREAD

**Issue by Mikenike2438** [NoiTheCat/WorldTime#16]
I was trying to put my timezone it didn't work the owner if the server that im in tried it doesn't work

**Comment by NoiTheCat** [comment]
Hello,
The bot does not accept three- or four-letter time zone abbreviations, as they can be pretty ambiguous. As described in the bot's `/help` command, time zones need to be from the IANA Time Zone Database, with the recommendation of using this to find the exact name to use: https://kevinnovak.github.io/Time-Zone-Picker/
